astra_db:
  collection_name: "rag_customer"
# Configuration file for the Astra DB connection


embedding_model:
  provider: "google"
  model_name: "models/gemini-embedding-001"



retriever:
  top_k: 3


# llm:
#   provider: "google"
#   model_name: "gemini-2.5-flash"

llm:
  provider: "groq"
  model_name: "llama-3.1-8b-instant"

pinecone:
  index_name: "customer-support-index"